### ISSUE TITLE
Sponser button goes to invalid url

### ISSUE THREAD

**Issue by angelblade27** [jahed/.github#1]
When clicking on the sponsor button ( to the left of the watch button) it shows this
![image](https://user-images.githubusercontent.com/13990173/66770383-5adfb600-ee6c-11e9-8671-d27ab5cfd03e.png)

Looks to be a typo in the FUNDING.yml. It should be "ko_fi" rather than "ko-fi

**Comment by angelblade27** [comment]
Should have a pull request done in couple minutes

**Comment by jahed** [comment]
Apologies I didn't see this sooner, I wasn't watching the repo. PR has been merged.

Thanks.
